/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package migrasidata2.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import migrasidata2.database.Database;
import migrasidata2.konfigurasi.Konfigurasi;

/**
 *
 * @author Kaitero
 */
public class FormConfigurasiOracle extends javax.swing.JFrame {

    /**
     * Creates new form FormConfigurasiOracle
     */
    private static FormConfigurasiOracle fco;
    private Konfigurasi konf = new Konfigurasi();
    private Database db = Database.getPk();
    private String url = "";
    private String port = "";
    private String schema = "";
    private String password = "";

    public static FormConfigurasiOracle getConfOra() {
        synchronized (FormConfigurasiOracle.class) {
            if (fco == null) {
                fco = new FormConfigurasiOracle();
            }
        }
        return fco;
    }

    private FormConfigurasiOracle() {
        initComponents();
        tfPassword.setEchoChar('*');
        konf.loadKonfigurasiOracle();
        setLocationRelativeTo(null);
        kondisiAwal();
        beforeConnect();
        btnSave.setEnabled(false);
        loadKonfigurasi();
        pack();
    }

    public void loadKonfigurasi() {
        tfUrl.setText(konf.getUrl());
        tfPort.setText(konf.getPort());
        tfUser.setText(konf.getUser());
        tfPassword.setText(konf.getPassword());
    }

    public void beforeConnect() {
        jComboBox1.setVisible(false);
        jCheckBox2.setVisible(false);
        tfPasswordSchema.setVisible(false);
        btnpilih.setVisible(false);
        btncreatesch.setVisible(false);
        btncreate.setVisible(false);
        tfUserBaru.setVisible(false);
        tfPasswordBaru.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }

    public void connect() {
        jComboBox1.setVisible(true);
        tfPasswordSchema.setVisible(true);
        btnpilih.setVisible(true);
        btncreatesch.setVisible(true);
        pack();
    }

    public void kondisiPilih() {
        tfUrl.setEditable(true);
        tfPort.setEditable(true);
        tfUser.setEditable(true);
        tfPassword.setEditable(true);
        btnSave.setEnabled(true);
    }

    public void kondisiAwal() {
        tfUrl.setEditable(false);
        tfPort.setEditable(false);
        tfUser.setEditable(false);
        tfPassword.setEditable(false);
        btnSave.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUrl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        btncreatesch = new javax.swing.JButton();
        tfPasswordSchema = new javax.swing.JTextField();
        btnpilih = new javax.swing.JButton();
        tfUserBaru = new javax.swing.JTextField();
        tfPasswordBaru = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("URL");

        jLabel2.setText("Port");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btncreatesch.setText("Create New Schema");
        btncreatesch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateschActionPerformed(evt);
            }
        });

        btnpilih.setText("Choose");
        btnpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memilihSchema(evt);
            }
        });

        tfUserBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserBaruKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUserBaruKeyTyped(evt);
            }
        });

        tfPasswordBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordBaruKeyTyped(evt);
            }
        });

        jLabel5.setText("User name");

        jLabel6.setText("Password");

        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Edit");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Grant DBA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tfPort)
                            .addComponent(tfUser)
                            .addComponent(tfPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncreatesch, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(tfPasswordSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnpilih))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUserBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jCheckBox2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnConnect)
                    .addComponent(btncancel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPasswordSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpilih))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreate)
                    .addComponent(btncreatesch))
                .addGap(11, 11, 11)
                .addComponent(jCheckBox2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bukaDB() {
        boolean sambung = db.bukaDBOracle(tfUrl.getText(), tfPort.getText(), tfUser.getText(), tfPassword.getText());
        if (sambung) {
            loadSchema();
            connect();
        } else {
            JOptionPane.showMessageDialog(null, "Maaf URL/User/Password yang anda masukan salah");
        }
    }
    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
//        db.setConn2(null);
        bukaDB();
    }//GEN-LAST:event_btnConnectActionPerformed

    public void loadSchema() {
        jComboBox1.removeAllItems();
        ResultSet rs = db.eksekusiSelectOracle("select username from dba_users");
        try {
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("username"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String url = tfUrl.getText();
        String port = tfPort.getText();
        String user = tfUser.getText();
        String password = tfPassword.getText();
        if (tfUrl.getText().trim().equals("") || tfPort.getText().trim().equals("") || tfUser.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf Harap Field URL/PORT/USER tidak boleh kosong");
        } else {
            JOptionPane.showMessageDialog(null, "Konfigurasi Data Oracle Berhasil Disimpan");
            konf.simpanConfigurasiOracle(url, port, user, password);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            kondisiPilih();
        } else {
            kondisiAwal();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btncreateschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateschActionPerformed
        // TODO add your handling code here:
        btncreatesch.setEnabled(false);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        tfPasswordBaru.setVisible(true);
        tfUserBaru.setVisible(true);
        btncreate.setVisible(true);
        btncreate.setEnabled(false);
        jCheckBox2.setVisible(true);
        pack();
    }//GEN-LAST:event_btncreateschActionPerformed

    private void tfUserBaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserBaruKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserBaruKeyPressed

    private void tfUserBaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserBaruKeyTyped
        if ((tfUserBaru.getText().trim().length() > 0) && (tfPasswordBaru.getText().trim().length() > 0)) {
            btncreate.setEnabled(true);
        } else {
            btncreate.setEnabled(false);
        }
    }//GEN-LAST:event_tfUserBaruKeyTyped

    private void tfPasswordBaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordBaruKeyTyped
        if ((tfUserBaru.getText().trim().length() > 0) && (tfPasswordBaru.getText().trim().length() > 0)) {
            btncreate.setEnabled(true);
        } else {
            btncreate.setEnabled(false);
        }
    }//GEN-LAST:event_tfPasswordBaruKeyTyped

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        String dba = "";
        boolean sukses = db.eksekusiQueryDMLOracle("create user " + tfUserBaru.getText().trim() + " identified by " + tfPasswordBaru.getText());
        if (sukses) {
            if (jCheckBox2.isSelected()) {
                boolean grant = db.eksekusiQueryDMLOracle("grant dba to " + tfUserBaru.getText());
                if (grant) {
                    dba = "sebagai DBA";
                }
            }
            JOptionPane.showMessageDialog(null, "User berhasil dibuat " + dba);
            loadSchema();
            btncreatesch.setEnabled(true);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            tfPasswordBaru.setVisible(false);
            tfUserBaru.setVisible(false);
            btncreate.setVisible(false);
            btncreate.setEnabled(false);
            jCheckBox2.setVisible(false);
            pack();
        }
    }//GEN-LAST:event_btncreateActionPerformed

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPort() {
        return port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    public String getSchema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean refreshConnection() {
        boolean cek = db.bukaDBOracle(getUrl(), getPort(), getSchema(), getPassword());
        return cek;
    }


    private void memilihSchema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memilihSchema
        // TODO add your handling code here:
        setUrl(tfUrl.getText());
        setPort(tfPort.getText());
        setSchema(jComboBox1.getSelectedItem().toString());
        setPassword(tfPasswordSchema.getText());
        if (tfPasswordSchema.getText().equals("") || tfPasswordSchema.getText().equals(null)) {
            JOptionPane.showMessageDialog(null, "Maaf Password tidak boleh kosong");
        } else {
            boolean cek = refreshConnection();
            if (cek) {
                JOptionPane.showMessageDialog(null, "Berhasil Terhubung dengan user");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Terhubung dengan user");
            }
        }
    }//GEN-LAST:event_memilihSchema

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btncreatesch;
    private javax.swing.JButton btnpilih;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPasswordBaru;
    private javax.swing.JTextField tfPasswordSchema;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfUrl;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUserBaru;
    // End of variables declaration//GEN-END:variables
}
