/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package migrasidata2.subview;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import migrasidata2.database.ColumnDescription;
import migrasidata2.database.Database;
import migrasidata2.database.DatabaseInformation;
import migrasidata2.database.KeyDescription;
import migrasidata2.pluginsclass.AutoResizeTable1;
import migrasidata2.view.FormUtama;

/**
 *
 * @author Kaitero
 */
public class PanelTabelMySQL extends javax.swing.JPanel {

    private DatabaseInformation di = new DatabaseInformation();
    private ArrayList<String> listTable;
    private ArrayList<String> isiTable;
    private ArrayList<ColumnDescription> listStruktur;
    private ArrayList<KeyDescription> listKey;
    private DefaultListModel model = new DefaultListModel();
    private DefaultTableModel tabmod1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    private DefaultTableModel tabmod2 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    private DefaultTableModel tabmod3 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    private Database db = Database.getPk();
    private AutoResizeTable1 a1 = new AutoResizeTable1();

    /**
     * Creates new form PanelTabelOracle
     */
    public PanelTabelMySQL() {
        initComponents();
        listTable = di.loadListTable("mysql");
        if (listTable.size() != 0) {
            setTableToList();
            jList1.setModel(model);
            jTable1.setModel(tabmod1);
            jTable2.setModel(tabmod2);
            jTable3.setModel(tabmod3);
        }else{
            JOptionPane.showMessageDialog(null, "Maaf Tidak ada tabel yang ditemukan");
        }
    }

    public void setTableToList() {
        for (int i = 0; i < listTable.size(); i++) {
            model.addElement(listTable.get(i));
        }
    }

    public void refreshTabel() {
        tabmod1.setRowCount(0);
        tabmod1.setColumnCount(0);
        tabmod2.setRowCount(0);
        tabmod2.setColumnCount(0);
        tabmod3.setRowCount(0);
        tabmod3.setColumnCount(0);
    }

    public void setStrukturToTabel() {
        String koma = "";
        tabmod1.setColumnIdentifiers(new Object[]{"TABLE", "AUTO INCREMENT", "COLUMN NAME", "COLUMN TYPE", "COLUMN SIZE", "NULLABLE"});
        for (int i = 0; i < listStruktur.size(); i++) {
            tabmod2.addColumn(listStruktur.get(i).getNamaKolom());
            if (listStruktur.get(i).getKomaKolom() > 0) {
                koma = listStruktur.get(i).getPanjangkolom() + "," + listStruktur.get(i).getKomaKolom();
            } else {
                koma = String.valueOf(listStruktur.get(i).getPanjangkolom());
            }
            tabmod1.insertRow(i, new Object[]{listStruktur.get(i).getNamaKelas(), listStruktur.get(i).isCekIncrements(), listStruktur.get(i).getNamaKolom(), listStruktur.get(i).getTipedata(), koma, listStruktur.get(i).nullAbles()});
        }
    }

    public void setDataToTabel() {
        for (int i = 0; i < isiTable.size(); i++) {
            String isi[] = isiTable.get(i).split(";");
            tabmod2.insertRow(i, isi);
        }
    }

    public void setKeyToTabel() {
        tabmod3.setColumnIdentifiers(new Object[]{"COLUMN NAME", "CONSTRAINT TYPE", "KEY NAME", "COLUMN REFRENCES", "SOURCE TABLE"});
        for (int i = 0; i < listKey.size(); i++) {
            tabmod3.insertRow(i, new Object[]{listKey.get(i).getNamaKolom(), listKey.get(i).getJenisKey(), listKey.get(i).getNamaKey(), listKey.get(i).getAsalKey(), listKey.get(i).getNamaTabel()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Column Description", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data On Tables", jPanel3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Constraint On Tables", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if (jList1.getSelectedIndex() != -1) {
            String tabel = jList1.getSelectedValue().toString();//ambil isinya
//            ResultSet
            ResultSet rs = db.eksekusiSelect("select * from " + tabel);
            try {
                ResultSetMetaData rsmd = rs.getMetaData();
                listStruktur = di.loadStruktur(rsmd, tabel);
                isiTable = di.loadIsiData(rs, rsmd.getColumnCount());
                listKey = di.loadAllKeys("mysql", tabel);
                refreshTabel();
                setStrukturToTabel();
                setDataToTabel();
                setKeyToTabel();
                a1.sesuaikanKolom(jTable1);
                a1.sesuaikanKolom(jTable2);
                a1.sesuaikanKolom(jTable3);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
